trigger:
- main

pool:
  name: Default    # Specify the name of your agent pool. The default pool will work if you're using the default agent pool.
  demands:
    - agent.os -equals Windows_NT  # Ensure the pipeline runs on a Windows agent.

jobs:
- job: BuildAndTest
  pool:
    name: Default    # Specify your local agent pool here (it could be a custom pool, not just Default)
  maxConcurrency: 1   # Limit to 1 job at a time (if needed)

  steps:
  - checkout: self
    fetchDepth: 1  # Fetch only the latest commit from the repo

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
