trigger:
  - main

# tell the JavaToolInstaller where your Zulu‑17 really lives
variables:
  JAVA_HOME_17_X64: 'C:\Program Files\Zulu\zulu-17'

pool:
  name: Default

jobs:
- job: Build
  steps:

    # 1) point the installer at your pre‑installed JDK
    - task: JavaToolInstaller@0
      displayName: 'Activate Java 17 (Zulu)'
      inputs:
        versionSpec: '17'               # major version
        jdkArchitectureOption: 'x64'    # matches your install
        jdkSourceOption: 'PreInstalled' # use the env var above

    # 2) run Maven, telling it to use the JDK we just activated
    - task: Maven@3
      displayName: 'Maven: clean package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'     # pick up the JDK from JavaToolInstaller
        jdkVersionOption: '17'           # must match versionSpec
        jdkArchitectureOption: 'x64'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
