trigger:
- main

pool:
  name: Default    # Replace with your custom agent pool name if needed
  demands:
    - agent.os -equals Windows_NT
    - JAVA_HOME_17_X64  # Ensure that JAVA_HOME_17_X64 exists

steps:
- checkout: self
  fetchDepth: 1  # Fetch only the latest commit from the repo

- task: Maven@4  # Use the latest version of Maven task
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'None'  # Don't specify custom Java home
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

env:
  JAVA_HOME: $(JAVA_HOME_17_X64)  # Set the JAVA_HOME environment variable to your existing Java installation
