trigger:
  - main

pool:
  name: Default

jobs:
- job: Build
  steps:
    - task: Maven@4
      displayName: 'Maven@4: clean package'
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
