trigger:
- main

pool:
  name: Default

jobs:
- job: Build
  steps:
    - script: |
        echo Setting up Java 17 environment
        set JAVA_HOME="C:\Program Files\Zulu\zulu-17"
        set PATH=%JAVA_HOME%\bin;%PATH%
        echo JAVA_HOME is set to %JAVA_HOME%
      displayName: 'Set up Java 17'
      shell: cmd

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'Custom'
        customJavaHome: 'C:\Program Files\Zulu\zulu-17'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
      displayName: 'Run Maven Build'
