trigger:
- main

pool:
  name: Default

jobs:
- job: Build
  steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'Custom'
        customJavaHome: 'C:\Program Files\Zulu\zulu-17'  # Directly specify Java path
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
      displayName: 'Run Maven Build'
