trigger:
- main

pool:
  name: Default
  demands:
    - agent.os -equals Windows_NT

steps:
- checkout: self
  fetchDepth: 1

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'          # Use your installed version
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
