trigger:
  - main

pool:
  name: Default

jobs:
- job: Build
  steps:
    - task: Maven@4
      displayName: 'Maven@4: clean package'
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    # Publish the build artifact
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        PathtoPublish: 'target' # This is where Maven typically places the JAR file
        ArtifactName: 'drop'    # You can name the artifact
        publishLocation: 'Container'
